language: node_js
dist: xenial
node_js:
  - 6
  - 8
  - 10
  - 12
script:
  - node --version
  - yarn --version
  - yarn run test
  - yarn run lint
notifications:
  email:
    on_failure: change
cache:
  yarn: true
  directories:
    - node_modules
